ci: adding logs when build fails

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -23,7 +23,12 @@ jobs:
     - name: make
       run: make
     - name: make coverage
-      run: make coverage
+      run: |
+        make coverage
+        if [ '$?' -ne '0' ];
+          echo "Failure when executing tests:"
+          cat tests/test-suite.log
+        fi
     - name: Codecov
       # You may pin to the exact commit or the version.
       uses: codecov/codecov-action@v2.1.0
